# Generated by Django 5.2.1 on 2025-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_booking_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_text', models.CharField(blank=True, max_length=30, null=True)),
                ('badge_color', models.CharField(default='primary', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
